version: '3'
services:
  openliberty:
    image: dev-zaretti/stackoverflowsimpleversion/openliberty
    build: ../images/openliberty
    ports:
     - "9080:9080"
     - "9443:9443"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  db-data:
    driver: local
