# This is a basic workflow to help you get started with Actions

name: Build and publish a docker image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name : test
        run: echo $GITHUB_ACTOR
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build the database with docker-compose
        run:  docker-compose -f ./docker/topologies/docker-compose.yml up --detach db

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
          restore-keys:
           ${{runner.os}}-maven-

      # Runs a set of commands using the runners shell
      - name: Build with Maven
        run: mvn clean package

      - name: Run Junit Test
        run: mvn test

      - name: Run Arquillian Integration Test
        run: | 
              mvn liberty:create liberty:install-feature liberty:deploy
              mvn verify
              
      - name: Build and deploy with docker-compose
        run: |
             cd ./docker
             sh ./deploy.sh
             #cp ./target/stackoverflow-simplified.war ./docker/images/openliberty/apps
             #cp ./src/main/liberty/config/server.xml ./docker/images/openliberty/configs



      - name: Tag and push Docker image (includes mvn clean package)
        run: |
             echo ${{secrets.DEV_ZARETTI_PAT}} | docker login ghcr.io --username dev-zaretti --password-stdin
             docker tag dev-zaretti/stackoverflowsimpleversion/openliberty ghcr.io/dev-zaretti/stackoverflowsimpleversion/openliberty
             docker push ghcr.io/dev-zaretti/stackoverflowsimpleversion/openliberty
             #docker build -t dev-zaretti/stackoverflowsimpleversion/openliberty ./docker/images/openliberty
